version: '3.7'

services:
  php-httpd:
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - "../.:/var/www/html"

  mariadb:
    image: mariadb:10.5.2
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'zepp'
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: 'basic_table'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - 'mariadb:db'
    ports:
      - 8081:80

volumes:
  mariadb-volume: